[platformio]
default_envs = PonyPlay

[common]
i2s_lib = ${platformio.packages_dir}/framework-arduinopico/libraries/I2S

[env:PonyPlay]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = PonyPlay
framework = arduino
board_build.core = earlephilhower
board_build.f_cpu = 240000000L
board_build.flash_size = 16MB
board_build.psram_cs = 4
board_build.usb_mode = 1
board_build.usb_cdc = 1
upload_protocol = picoprobe
debug_tool = picoprobe
monitor_speed = 115200
build_flags =
	-DUSE_TINYUSB
	-DARDUINO_ARCH_RP2040
	-DARDUINO_PONY_PLAY
	-DRP2350_PSRAM_CS=4
	-O2
	-DENABLE_DEDICATED_SPI=1
	-mcpu=cortex-m33+nodsp
	-mfpu=fpv5-sp-d16
	-mfloat-abi=hard
	-ffast-math
	-DUSE_PICOPROBE
	-DDEBUG=0
lib_deps =
	${common.i2s_lib}
	adafruit/SdFat - Adafruit Fork@2.3.103
	adafruit/Adafruit TinyUSB Library@3.7.4
	adafruit/Adafruit BusIO@1.17.4
	adafruit/Adafruit NeoPixel@1.15.4
	thomasfredericks/Bounce2@2.72
	pico_multicore
	deanisme/SevSeg@3.7.2