; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = ./

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = fantasia_rp
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 1m
board_build.variants_dir = variants
build_flags = -DUSE_TINYUSB
monitor_speed = 115200
lib_deps = 
	adafruit/Adafruit TinyUSB Library@^3.7.0
	fortyseveneffects/MIDI Library @ ^5.0.2
	adafruit/Adafruit BusIO @ ^1.9.3
	adafruit/Adafruit NeoPixel
	thomasfredericks/Bounce2@^2.55
	git+https://github.com/ciutadellla/pico-audio.git#audio-input
	git+https://github.com/thomasvanta/SevenSegment
	pmarques-dev/PicoEncoder @ ^1.1.1
